### ISSUE TITLE
Font Family

### ISSUE THREAD

**Issue by sjlagasse** [juliabarrett/prj-rev-bwfs-dasmoto#4]
https://github.com/juliabarrett/prj-rev-bwfs-dasmoto/blob/0048e2e771c5551449ec7812454c220003e6b04c/Dasmoto/resources/css/style.css#L1-L6

You were probably coding this and wondering if there was an easier way to do it. In fact, there is! Try setting your `font-family` like this:

```
html {
  font-family: "Helvetica", sans-serif;
}
```

You could also use `body` too. Any over arching parent element will do.

**Comment by juliabarrett** [comment]
I knew I didn't want to use *, but couldn't think of what else was okay...now I will as that was annoying.
